name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: yarn

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: aws_cloudresume/frontend/
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: eu-central-1
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true